name: CI

on:
  pull_request_review_comment:
    
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - name: Run a multi-line script
        run: |
          env
