name: jenkins trigger

on:
  issue_comment:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - name: Run a multi-line script
        run: |
          echo $GITHUB_EVENT_NAME
          curl -X POST --oauth2-bearer test --json @$GITHUB_EVENT_PATH http://88.201.251.132/generic-webhook-trigger/invoke
          env
