name: CI

on:
  pull_request_review_comment:
  commit_comment:
  discussion_comment:
  pull_request_review:
  issue_comment:
  
    
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - name: Run a multi-line script
        run: |
          set -x
          env
          cat $GITHUB_EVENT_PATH
          echo $GITHUB_EVENT_NAME
