on:
  workflow_dispatch:

jobs:
  test-prefix:
    if: ${{ startsWith(github.ref_name, 'prefix') }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: hello prefix
        run: echo Hello, prefix!

  test-non-prefix:
    if: ${{ ! startsWith(github.ref_name, 'prefix') }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: hello
        run: echo Hello, something!
